version: '3.8'

services:
  # --- Service 1: Database (MySQL) ---
  mysqldb:
    image: mysql:8.0
    container_name: travel_db_container
    environment:
      - MYSQL_ROOT_PASSWORD=1  # Mật khẩu root
      - MYSQL_DATABASE=dacn2 # Tên DB tự tạo
    ports:
      - "3307:3306" # Map cổng 3306 trong docker ra 3307 ngoài máy (để tránh đụng cổng nếu máy bạn có sẵn mysql)
    volumes:
      - db_data:/var/lib/mysql # Để dữ liệu không mất khi tắt docker

  # --- Service 2: Spring Boot App ---
  springboot-app:
    build: . # Build từ Dockerfile ở thư mục hiện tại
    container_name: travel_app_container
    ports:
      - "8080:8080" # Cổng web
    depends_on:
      - mysqldb # Chờ DB chạy xong mới chạy App
    environment:
      # CẤU HÌNH QUAN TRỌNG: Ghi đè file properties
      # Lưu ý: 'mysqldb' ở đây chính là tên service ở trên, KHÔNG dùng localhost
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/dacn2?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update # Tự động tạo bảng

volumes:
  db_data: