version: "3.8"
services:
  elasticsearch:
    image: elasticsearch:8.11.1
    container_name: dacn2-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - dacn2-net

  redis:
    image: redis:latest
    container_name: dacn2-redis
    ports:
      - "6379:6379"
    networks:
      - dacn2-net

networks:
  dacn2-net:
    driver: bridge

volumes:
  es_data:
